### PR TITLE
Fix deterministic bridge shutdown by tracking component tasks

### LINKED ISSUE #21: Bridge shutdown sends Stop but does not wait for component completion
During shutdown, bridge sends `Message::Stop` to all component channels, but returns without waiting for components to finish graceful termination.

Current code pattern:
```rust
for tx in &self.input_txs {
    let _ = tx.send(Message::Stop).await;
}
for tx in &self.pipeline_txs {
    let _ = tx.send(Message::Stop).await;
}
for tx in &self.remote_txs {
    let _ = tx.send(Message::Stop).await;
}
```

### Expected behavior
After sending `Stop`, bridge should wait for all components/tasks to finish (or time out explicitly), so shutdown is deterministic and graceful.

### Actual behavior
Bridge only dispatches stop messages and can exit while components are still processing/cleaning up.

### Why this is a problem
- Possible in-flight data loss during shutdown
- Non-deterministic termination order
- Harder to reason about resource cleanup and task lifecycle

### Suggested fix
Track task `JoinHandle`s (or completion acknowledgements) for inputs/pipeline/remotes and await them after stop broadcast, with optional shutdown timeout and logging for stuck tasks.

### Repro
1. Start bridge with active inputs/pipeline/remotes.
2. Trigger shutdown.
3. Observe process/manager returns before all worker tasks complete.

### PR DESCRIPTION
**Pull request by tuanhungngyn**
Closes #21

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix

### What was changed?

- added a shared `ComponentRuntime` wrapper to keep each component control channel together with its `JoinHandle`
- updated input, pipeline, and remote launchers to return tracked runtimes instead of only senders
- changed `PipelineRuntime` to own inputs, fan-outs, pipelines, and remotes and shut them down in stages
- stopped forwarding downstream `Message::Stop` from individual inputs and pipelines so shared consumers are not terminated early
- updated direct launcher tests to use the new runtime wrapper and verify clean task shutdown

### Related issues

- #21 Bridge shutdown sends Stop but does not wait for component completion

### Does this PR introduce a breaking change?

No user-facing breaking change is intended. This changes internal shutdown coordination only.

### Other information:

Validation:
- `cargo test`

### CODE REVIEW

File: src/pipeline.rs [hunk 1]
```diff
@@ -261,23 +275,63 @@ impl PipelineLauncher for PassthroughPipelineLauncher {
 }
 
 pub struct PipelineRuntime {
-    input_txs: Vec<Sender<Message>>,
-    pipeline_txs: Vec<Sender<Message>>,
-    remote_txs: Vec<Sender<Message>>,
+    inputs: Vec<ComponentRuntime>,
+    fanouts: Vec<ComponentRuntime>,
```
Comment (atimin) [inline src/pipeline.rs]: what's what?

File: src/pipeline.rs [hunk 2]
```diff
@@ -261,23 +275,63 @@ impl PipelineLauncher for PassthroughPipelineLauncher {
...
 
 impl PipelineRuntime {
-    pub async fn stop(&self) {
-        for tx in &self.input_txs {
-            let _ = tx.send(Message::Stop).await;
-        }
-        for tx in &self.pipeline_txs {
-            let _ = tx.send(Message::Stop).await;
+    async fn stop_stage(stage: Vec<ComponentRuntime>, deadline: Instant) {
+        let mut pending = stage;
```
Comment (atimin) [inline src/pipeline.rs:278]: Let's keep it simple. We don't need a deadline; we can just wait forever. I think that's fine for this type of communication.

**Review by atimin — CHANGES_REQUESTED** [review]

File: src/pipeline.rs (hunk 1 above)
Comment (tuanhungngyn) [reply src/pipeline.rs]: I'm changing the name, it's the router for input to pipeline.

**Review by atimin — CHANGES_REQUESTED** [review]
one thing I missed:

```

    info!("Waiting for Ctrl+C");
    tokio::signal::ctrl_c()
        .await
        .context("Failed to listen for Ctrl+C")?;

```

this is portable way to stop a process from the console. However, docker and systemd send SIGTERM, which is only for  unix systems.  We have to handle both signals.

**Review by atimin — APPROVED** [review]
Perfect!
